# Generated by Django 4.2.14 on 2024-10-22 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='depth',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='numchild',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='path',
        ),
        migrations.AddField(
            model_name='unit',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='api.unit', verbose_name='Родитель'),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.unit', verbose_name='Подразделение'),
        ),
    ]
